# Generated by Django 4.2.7 on 2025-04-06 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("url_imagen", models.CharField(max_length=300)),
                ("descripcion", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("fecha_publicacion", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("direccion", models.CharField(max_length=500)),
                ("fecha_venta", models.DateField(auto_now_add=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.producto"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
