# Generated by Django 4.2.7 on 2025-04-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_blog_venta_delete_compra_delete_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="descripcion",
            field=models.CharField(max_length=200),
        ),
    ]
