# Generated by Django 4.2.7 on 2025-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_blog_url_imagen_alter_producto_url_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="producto",
            name="marca",
            field=models.CharField(
                choices=[
                    ("Games Workshop", "Games Workshop"),
                    ("Corvus Belli", "Corvus Belli"),
                    ("Warlord Games", "Warlord Games"),
                    ("Vallejo", "Vallejo"),
                    ("Army Painter", "Army Painter"),
                    ("Citadel Colour", "Citadel Colour"),
                ],
                default="JR",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blogs", to="shop.tag"
            ),
        ),
    ]
