# Generated by Django 4.2.7 on 2025-04-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_tag_alter_producto_marca_blog_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="producto",
        ),
        migrations.AddField(
            model_name="venta",
            name="productos",
            field=models.ManyToManyField(to="shop.producto"),
        ),
        migrations.AlterField(
            model_name="venta",
            name="id",
            field=models.CharField(
                max_length=12, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
