# Generated by Django 4.2.7 on 2025-04-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_remove_venta_producto_venta_productos_alter_venta_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="codigo_postal",
            field=models.CharField(default=20000, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venta",
            name="correo",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venta",
            name="estado",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venta",
            name="telefono",
            field=models.CharField(default=449000000, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venta",
            name="tipo",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
