# Generated by Django 4.2.7 on 2025-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_venta_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="url_imagen",
            field=models.ImageField(upload_to=""),
        ),
    ]
