# Generated by Django 4.2.7 on 2025-04-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_ventaproducto"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="detalles",
            field=models.ManyToManyField(
                related_name="ventas", through="shop.VentaProducto", to="shop.producto"
            ),
        ),
    ]
