# Generated by Django 4.2.7 on 2025-04-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_venta_detalles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="productos",
        ),
    ]
