# Generated by Django 4.2.7 on 2025-04-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_remove_venta_productos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="url_imagen",
            new_name="imagen",
        ),
    ]
