# Generated by Django 4.2.7 on 2025-04-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_rename_url_imagen_producto_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="url_imagen",
        ),
        migrations.AddField(
            model_name="blog",
            name="imagen",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
