# Generated by Django 4.2.7 on 2026-07-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_blog_url_imagen_blog_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaEnvio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cuota de Envío',
                'verbose_name_plural': 'Cuotas de Envío',
            },
        ),
    ]
