# Generated by Django 4.2.7 on 2026-09-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cuotaenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
